version: 2
updates:
  # Aktualisierung der npm-Abhängigkeiten
  - package-ecosystem: "npm"
    directory: "/"  # Pfad zum Projektverzeichnis
    schedule:
      interval: "weekly"  # Prüft wöchentlich auf Updates
    open-pull-requests-limit: 10 # Maximale Anzahl offener PRs
    reviewers:  # Optionale Reviewer zuweisen
      - "huberp"
    assignees:
      - "huberp"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "javascript"
